apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: facebook
  name: facebook
spec:
  replicas: 4
  selector:
    matchLabels:
      app: facebook2
  template:
    metadata:
      labels:
        app: facebook2
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: nginx
        name: nginx
